import { StyleSheet, Platform } from 'react-native';
import { COLORS } from './constants';

export const styles = StyleSheet.create({
    screenContainer: {
        flex: 1,
        backgroundColor: COLORS.lightGray,
    },
    keyboardAvoidingContainer: {
        flex: 1,
    },
    centeredContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 30,
    },
    emptyText: {
        marginTop: 15,
        fontSize: 18,
        color: COLORS.textGray,
    },
    emptySubText: {
        marginTop: 5,
        fontSize: 14,
        color: COLORS.mediumGray,
        textAlign: 'center',
    },
    listContainer: {
        flex: 1,
    },
    listContentContainer: {
        paddingTop: 10,
        paddingBottom: 10,
    },
    separator: {
        height: 10,
    },
    postCard: {
        backgroundColor: COLORS.postBackground,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginHorizontal: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: COLORS.borderColor,
        elevation: 1,
    },
    postHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    avatarContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.avatarBackground,
        marginRight: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarText: {
        color: COLORS.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    postHeaderText: {
        flex: 1,
    },
    authorName: {
        fontWeight: '600',
        color: COLORS.darkGray,
        fontSize: 15,
        marginBottom: 2,
    },
    timestamp: {
        fontSize: 12,
        color: COLORS.textGray,
    },
    postText: {
        fontSize: 15,
        lineHeight: 22,
        color: COLORS.darkGray,
        marginBottom: 12,
    },
    postFooter: {
        flexDirection: 'row',
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: COLORS.borderColor,
    },
    footerAction: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 20,
    },
    footerActionText: {
        marginLeft: 5,
        fontSize: 13,
        color: COLORS.textGray,
    },
    inputOuterContainer: {
        paddingHorizontal: 10,
        paddingBottom: Platform.OS === 'ios' ? 10 : 5,
        paddingTop: 5,
        borderTopWidth: 1,
        borderTopColor: COLORS.borderColor,
        backgroundColor: COLORS.white,
    },
    postingErrorText: {
        color: COLORS.errorRed,
        fontSize: 12,
        textAlign: 'center',
        marginBottom: 4,
    },
    inputInnerContainer: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        backgroundColor: COLORS.inputBackground,
    },
    textInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: COLORS.mediumGray,
        borderRadius: 20,
        paddingHorizontal: 15,
        paddingVertical: Platform.OS === 'ios' ? 10 : 8,
        paddingTop: Platform.OS === 'ios' ? 10 : 8,
        marginRight: 8,
        backgroundColor: COLORS.white,
        fontSize: 16,
        maxHeight: 100,
        color: COLORS.darkGray,
    },
    postButton: {
        padding: 10,
        borderRadius: 20,
        backgroundColor: COLORS.lightGray,
        justifyContent: 'center',
        alignItems: 'center',
        height: 40,
        width: 40,
    },
    buttonDisabled: {
        opacity: 0.5,
    },
    errorTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: COLORS.errorRed,
        marginTop: 15,
        marginBottom: 8,
        textAlign: 'center',
    },
    errorTextDetail: {
        color: COLORS.textGray,
        textAlign: 'center',
        marginBottom: 25,
        fontSize: 16,
    },
    retryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.primaryBlue,
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 25,
        elevation: 2,
    },
    retryButtonText: {
        color: COLORS.white,
        fontSize: 16,
        marginLeft: 10,
        fontWeight: '500',
    },
    replyContainer: {
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: COLORS.borderColor,
    },
    replyInput: {
        backgroundColor: COLORS.lightGray,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 14,
        marginBottom: 10,
        minHeight: 50,
        textAlignVertical: 'top',
        borderWidth: 1,
        borderColor: COLORS.mediumGray,
    },
    replyActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    replyButton: {
        paddingHorizontal: 15,
        paddingVertical: 8,
        borderRadius: 6,
        marginLeft: 10,
    },
    cancelReplyButton: {
        backgroundColor: COLORS.white,
        borderWidth: 1,
        borderColor: COLORS.mediumGray,
    },
    submitReplyButton: {
        backgroundColor: COLORS.primaryBlue,
    },
    replyButtonText: {
        fontSize: 14,
        fontWeight: '500',
        color: COLORS.darkGray,
    },
    submitReplyButtonText: {
        color: COLORS.white,
    },
    replyErrorText: {
        color: COLORS.errorRed,
        fontSize: 13,
        marginBottom: 5,
        textAlign: 'right',
    },
    repliesContainer: {
        marginTop: 10,
        marginLeft: 20,
        paddingLeft: 15,
        borderLeftWidth: 2,
        borderLeftColor: COLORS.mediumGray,
    },
    replyItemContainer: {
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.borderColor,
    },
    replyHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 5,
    },
    replyAvatarContainer: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: COLORS.avatarBackground,
        marginRight: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    replyAvatarText: {
        color: COLORS.white,
        fontSize: 10,
        fontWeight: 'bold',
    },
    replyHeaderText: {
        flex: 1,
    },
    replyAuthorName: {
        fontWeight: '600',
        color: COLORS.darkGray,
        fontSize: 13,
        marginBottom: 1,
    },
    replyTimestamp: {
        fontSize: 11,
        color: COLORS.textGray,
    },
    replyText: {
        fontSize: 14,
        lineHeight: 19,
        color: COLORS.darkGray,
    },
}); 